// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_matrix_multiply
NumericMatrix cpp_matrix_multiply(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _mylm_cpp_matrix_multiply(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_matrix_multiply(A, B));
    return rcpp_result_gen;
END_RCPP
}
// cpp_matrix_transpose
NumericMatrix cpp_matrix_transpose(NumericMatrix A);
RcppExport SEXP _mylm_cpp_matrix_transpose(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_matrix_transpose(A));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mylm_cpp_matrix_multiply", (DL_FUNC) &_mylm_cpp_matrix_multiply, 2},
    {"_mylm_cpp_matrix_transpose", (DL_FUNC) &_mylm_cpp_matrix_transpose, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mylm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
