# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_matrix_multiply <- function(A, B) {
    .Call(`_mylm_cpp_matrix_multiply`, A, B)
}

cpp_matrix_transpose <- function(A) {
    .Call(`_mylm_cpp_matrix_transpose`, A)
}

